package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CuisineTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuisineTypeAllPropertiesEquals(CuisineType expected, CuisineType actual) {
        assertCuisineTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCuisineTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuisineTypeAllUpdatablePropertiesEquals(CuisineType expected, CuisineType actual) {
        assertCuisineTypeUpdatableFieldsEquals(expected, actual);
        assertCuisineTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuisineTypeAutoGeneratedPropertiesEquals(CuisineType expected, CuisineType actual) {
        assertThat(expected)
            .as("Verify CuisineType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuisineTypeUpdatableFieldsEquals(CuisineType expected, CuisineType actual) {
        assertThat(expected)
            .as("Verify CuisineType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuisineTypeUpdatableRelationshipsEquals(CuisineType expected, CuisineType actual) {}
}
