package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllPropertiesEquals(MenuItem expected, MenuItem actual) {
        assertMenuItemAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllUpdatablePropertiesEquals(MenuItem expected, MenuItem actual) {
        assertMenuItemUpdatableFieldsEquals(expected, actual);
        assertMenuItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAutoGeneratedPropertiesEquals(MenuItem expected, MenuItem actual) {
        assertThat(expected)
            .as("Verify MenuItem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemUpdatableFieldsEquals(MenuItem expected, MenuItem actual) {
        assertThat(expected)
            .as("Verify MenuItem relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").isEqualTo(actual.getPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemUpdatableRelationshipsEquals(MenuItem expected, MenuItem actual) {
        assertThat(expected)
            .as("Verify MenuItem relationships")
            .satisfies(e -> assertThat(e.getTruck()).as("check truck").isEqualTo(actual.getTruck()))
            .satisfies(e -> assertThat(e.getOrders()).as("check orders").isEqualTo(actual.getOrders()));
    }
}
